RazorTestTask/Pages/Administration.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorTestTask.Model;

namespace RazorTestTask.Pages
{
    public class AdministrationModel : PageModel
    {
        [BindProperty]
        public List<User> users { get; set; } = new List<User>();
        [BindProperty]
        public bool FlagUpdateUser { get; set; } = new();
        [BindProperty]
        public User userOld { get; set; } = new();
        [BindProperty]
        public User userNew { get; set; } = new();

        public void OnGet()
        {
            using(ApplicationDateBase db = new ApplicationDateBase())
            {
                users = db.Users.Include(p => p.Role).ToList();
            }
        }

        public void OnPostUpdate(string Name, string Role)
        {
            string[] name = Name.Split(' ',StringSplitOptions.RemoveEmptyEntries);

            using(ApplicationDateBase db = new ApplicationDateBase())
            {
                User userInDateBase = db.Users.Include(p => p.Role).Where(u => u.Name == name[1] && u.Subname == name[0] && u.Role.Name == Role).First();
                userOld = userInDateBase;
                userNew = userInDateBase;
            }

            FlagUpdateUser = true;
            OnGet();
        }

        public void OnPostUpdateUser()
        {

            using(ApplicationDateBase db = new ApplicationDateBase())
            {
                var userUpdate = db.Users.Include(s => s.Role).Where(u => u.Name == userOld.Name && u.Subname == userOld.Subname && u.Login == userOld.Login && u.Password == userOld.Password).First();

                userUpdate.Name = userNew.Name;
                userUpdate.Subname = userNew.Subname; 
                userUpdate.Login = userNew.Login;
                userUpdate.Password = userNew.Password;
                db.SaveChanges();

            }

            FlagUpdateUser = false;
            OnGet();
        }
    }
}

RazorTestTask/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorTestTask.Model;

namespace RazorTestTask.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public List<Product> products { get; set; } = new List<Product>();
        [BindProperty]
        public Product productInf { get; set; } = new();
        [BindProperty]
        public Product productOld { get; set; } = new();
        [BindProperty]
        public FormUser user { get; set; } = new();

        [BindProperty]
        public string userInSite { get; set; } = "Guest";
        [BindProperty]
        public bool FlagUpdateProduct { get; set; } = new();

        public void OnGet()
        {
            ReadProducts();
        }

        public void ReadProducts()
        {
            using(ApplicationDateBase db = new ApplicationDateBase())
            {
                products.AddRange(db.Products);
            }
        }

        public ActionResult OnPostAddProduct()
        {
            if (IsValidationProduct(productInf))
            {
                using (ApplicationDateBase db = new ApplicationDateBase())
                {
                    db.Products.Add(new Product { Name = productInf.Name, Quantity = productInf.Quantity });
                    db.SaveChanges();
                }
                return RedirectToPage("Index");
            }
            return null;
        }

        public ActionResult OnPostDeleteProduct()
        {
            using(ApplicationDateBase db = new ApplicationDateBase())
            {
                db.Products.Remove(new Product { Id = productInf.Id, Name = productInf.Name, Quantity = productInf.Quantity });
                db.SaveChanges();
            }
            return RedirectToPage("Index");
        }

        public void OnPostUpdateProduct()
        {
            using(ApplicationDateBase db = new ApplicationDateBase())
            {
                var product = db.Products.Where(s=>s.Name == productOld.Name && s.Quantity == productOld.Quantity).First();

                product.Name = productInf.Name;
                product.Quantity = productInf.Quantity;

                db.SaveChanges();
            }
            OnGet();
        }

        public void OnPostUpdateProductWindow()
        {
            productOld = productInf;

            FlagUpdateProduct = true;
            OnGet();
        }

        public void OnPostJoinUser()
        {
            if (IsValidationUserJoin(user))
            {
                using (ApplicationDateBase db = new ApplicationDateBase())
                {
                    var flag = db.Users.Any(s => s.Login == user.Login && s.Password == user.Password);
                    if (flag)
                    {
                        var userInDateBase = db.Users.Include(p=>p.Role).Where(s => s.Login == user.Login && s.Password == user.Password).FirstOrDefault();
                        if(userInDateBase.Role.Name == "Admin")
                        {
                            userInSite = "Admin";
                        }
                        else
                        {
                            userInSite = "User";
                        }
                    }
                }
            }
            OnGet();
        }

        private bool IsValidationProduct(Product product)
        {
            if (product.Name != null && product.Quantity > 0 && product.Quantity < 2000000) 
            {
                return true;
            }

            return false;
        }

        private bool IsValidationUserJoin(FormUser user)
        {
            if (user.Login != null && user.Password != null)
            {
                return true;
            }

            return false;
        }
    }
}

RazorTestTask/Pages/Registration.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorTestTask.Model;

namespace RazorTestTask.Pages
{
    public class RegistrationModel : PageModel
    {
        [BindProperty]
        public FormRegistrationUser user { get; set; } = new();

        public void OnGet()
        {

        }

        public ActionResult OnPost()
        {
            if(TryValidateModel(user, nameof(user))){
                
                using(ApplicationDateBase db = new ApplicationDateBase())
                {
                    db.Users.Add(new User { Name = user.Name, Subname = user.Subname, Login = user.Login, Password = user.Password, Role = db.Roles.Where(u => u.Name == "User").First() });
                    db.SaveChanges();
                }

                return RedirectToPage("Index");
            }
            return null;
        }
    }
}

RazorTestTask/Pages/Administration.cshtml
@page
@model AdministrationModel
@{
}

<html>
    <head>
        <link href="~/css/Administration.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/Table.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <div class="MainBody">
            <div class="Table">
                <div class="Row">
                    <div class="Colum">
                        <p>Name</p>
                    </div>
                    <div class="Colum">
                        <p>Role</p>
                    </div>
                    <div class="Colum ColumInf">

                    </div>
                   @* <div class="Colum ColumInf">

                    </div>*@
                </div>
                @foreach(var user in Model.users)
                {
                    <form method="post" style="margin:0">
                        <div class="Row">
                            <div class="Colum">
                                <input name="Name" value="@user.Subname @user.Name"/>
                            </div>
                            <div class="Colum">
                                <input name="Role" value="@user.Role.Name" />
                            </div>
                            <div class="Colum ColumInf">
                                <input type="submit" class="ButtomInf Butt" value="Update" asp-page-handler="Update"/>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>


        @if (Model.FlagUpdateUser)
        {
            <div class="BackBlack">
                <div class="WindowUpdateUser">
                    <form method="post">
                        <div>
                            <div>
                                <div>
                                    <label>Name</label>
                                </div>
                                <input asp-for="@Model.userNew.Name" />
                                <input asp-for="@Model.userOld.Name" value="@Model.userOld.Name" style="display:none" />
                            </div>
                            <div>
                                <div>
                                    <label>Subname</label>
                                </div>
                                <input asp-for="@Model.userNew.Subname" />
                                <input asp-for="@Model.userOld.Subname" value="@Model.userOld.Subname" style="display:none" />
                            </div>
                            <div>
                                <div>
                                    <label>Login</label>
                                </div>
                                <input asp-for="@Model.userNew.Login" />
                                <input asp-for="@Model.userOld.Login" value="@Model.userOld.Login" style="display:none" />
                            </div>
                            <div>
                                <div>
                                    <label>Password</label>
                                </div>
                                <input asp-for="@Model.userNew.Password" />
                                <input asp-for="@Model.userOld.Password" value="@Model.userOld.Password" style="display:none" />
                            </div>
                        </div>
                        <div>
                            <input type="submit" value="Submit" asp-page-handler="UpdateUser"/>
                            <a href="Administration">
                                <input type="button" value="Close" />
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        }

    </body>
</html>

RazorTestTask/Pages/Index.cshtml
@page
@model IndexModel
@{
}


<html>
    <head>
        <link href="~/css/Index.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/IndexJoinWindow.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/Table.css" rel="stylesheet" type="text/css"/>
        <link href="~/css/IndexWindowAdd.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <div class="Header">
            <div class="HeaderNav">
                @if (Model.userInSite == "Guest")
                {
                    <button class="Nav" onclick="onClickJoinSite()">Join</button>
                    <a href="Registration">
                        <button class="Nav">Registration</button>
                    </a>
                }
                @if(Model.userInSite == "User"){
                    <p>User</p>
                }
                @if (Model.userInSite == "Admin")
                {
                    <p>Hello administration</p>
                    @*<button class="Nav" onclick="onClickJoinSite()">Join</button>
                    <a href="Registration">
                        <button class="Nav">Registration</button>
                    </a>*@
                    <a href="Administration">Admin</a>
                }
            </div>
        </div>

        <div style="position:absolute; left:0px;top:50%;z-index:100">
            <button onclick="onClickAddProduct()">AddProduct</button>
        </div>


        <div class="BodyMain">
            <div class="Table">
                <div class="Row">
                    <div class="Colum">
                        <p>№</p>
                    </div>
                    <div class="Colum">
                        <p>Name</p>
                    </div>
                    <div class="Colum">
                        <p>Quantity</p>
                    </div>
                    <div class="Colum ColumInf">

                    </div>
                    <div class="Colum ColumInf">

                    </div>
                </div>
                @foreach(var product in Model.products)
                {
                    <form method="post" style="margin:0">
                        <div class="Row">
                            <div class="Colum">
                                <input type="text" asp-for="@Model.productInf.Id"  value="@product.Id.ToString()" />
                            </div>
                            <div class="Colum">
                                <input type="text" asp-for="@Model.productInf.Name" value="@product.Name"/>
                            </div>
                            <div class="Colum">
                                <input type="text" asp-for="@Model.productInf.Quantity" value="@product.Quantity.ToString()"/>
                            </div>
                            <div class="Colum ColumInf">
                                <input type="submit" asp-page-handler="UpdateProductWindow" class="ButtomInf Butt" value="Update">
                            </div>
                            <div class="Colum ColumInf">
                                <input type="submit" asp-page-handler="DeleteProduct" class="ButtomDelete Butt" value="Delete"/>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
        




        <div id="WindowCreateProduct" class="BlackBack">
            <div class="WindowAdd">
                <form method="post">
                    <div class="Inf">
                        <div class="BlockInf">
                            <div class="InfInput">
                                <label>Name</label>
                            </div>
                            <input asp-for="@Model.productInf.Name" class="InputInformation" type="text"/>
                            <span asp-validation-for="@Model.productInf.Name"></span>
                        </div>
                        <div class="BlockInf">
                            <div class="InfInput">
                                <label>Quantity</label>
                            </div>
                            <input asp-for="@Model.productInf.Quantity" class="InputInformation"  type="number" />
                            <span asp-validation-for="@Model.productInf.Quantity"></span>
                        </div>
                    </div>
                    <div class="ButtonPanel">
                        <input type="submit" value="Submit" asp-page-handler="AddProduct" />
                        <input type="button" onclick="onClickCloseAddProduct()" value="Close"/>
                    </div>
                </form>
            </div>
        </div>

        @if (Model.FlagUpdateProduct)
        {
            <div class="BlackBack" style="display:flex">
                <div class="WindowAdd">
                    <form method="post">
                        <div style="display:none">
                            <input name="oldName" value="@Model.productInf.Name"/>
                        </div>
                        <div class="Inf">
                            <div class="BlockInf">
                                <div class="InfInput">
                                    <label>Name</label>
                                </div>
                                <input asp-for="@Model.productOld.Name" style="display:none"/>
                                <input asp-for="@Model.productInf.Name" class="InputInformation" type="text" value="@Model.productInf.Name"/>
                                <span asp-validation-for="@Model.productInf.Name"></span>
                            </div>
                            <div class="BlockInf">
                                <div class="InfInput">
                                    <label>Quantity</label>
                                </div>
                                <input asp-for="@Model.productOld.Quantity" style="display:none"/>
                                <input asp-for="@Model.productInf.Quantity" class="InputInformation" type="number" value="@Model.productInf.Quantity"/>
                                <span asp-validation-for="@Model.productInf.Quantity"></span>
                            </div>
                        </div>
                        <div class="ButtonPanel">
                            <input type="submit" value="Submit" asp-page-handler="UpdateProduct" />
                            <a href="Index">
                                <input type="button" value="Close" />
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        }


        <div id="WindowsJoinInSite" class="BlackBack">
            <div class="WindowJoin">
                <form method="post">
                    <div class="InfInput">
                        <div class="InputAndLabel">
                            <div class="LabelCSS">
                                <label>Login</label>
                            </div>
                            <div>
                                <input asp-for="@Model.user.Login" class="InputCSS" type="text" />
                                <span asp-validation-for="@Model.user.Login"></span>
                            </div>
                        </div>
                        <div class="InputAndLabel">
                            <div class="LabelCSS">
                                <label>Password</label>
                            </div>
                            <div>
                                <input asp-for="@Model.user.Password" class="InputCSS" type="password" />
                                <span asp-validation-for="@Model.user.Password"></span>
                            </div>
                        </div>
                    </div>
                    <div class="InfInput">
                        <input type="submit" class="ButtonSubmit" value="Submit" asp-page-handler="JoinUser" />
                        <input onclick="onClickCloseWindowJoin()" type="button" class="ButtonSubmit" value="Close" />
                    </div>
                </form>
            </div>
        </div>

    </body>

    <script type="text/javascript" src="~/js/Index.js"></script>
</html>

RazorTestTask/Pages/Registration.cshtml
@page
@model RegistrationModel
@{
}

<html>
    <head>
        <link href="~/css/Registration.css" type="text/css" rel="stylesheet"/>
    </head>
    <body>
        <div>
            <form method="post">
                <div>
                    <div>
                        <label>Name</label>
                    </div>
                    <input type="text" asp-for="@Model.user.Name"/>
                    <span asp-validation-for="@Model.user.Name"></span>
                </div>
                <div>
                    <div>
                        <label>Subname</label>
                    </div>
                    <input type="text" asp-for="@Model.user.Subname"/>
                    <span asp-validation-for="@Model.user.Subname"></span>
                </div>
                <div>
                    <div>
                        <label>Login</label>
                    </div>
                    <input type="text" asp-for="@Model.user.Login"/>
                    <span asp-validation-for="@Model.user.Login"></span>
                </div>
                <div>
                    <div>
                        <label>Password</label>
                    </div>
                    <input type="password" asp-for="@Model.user.Password"/>
                    <span asp-validation-for="@Model.user.Password"></span>
                </div>
                <div>
                    <div>
                        <label>Password №2</label>
                    </div>
                    <input type="password" asp-for="@Model.user.DoublePassword"/>
                    <span asp-validation-for="@Model.user.DoublePassword"></span>
                </div>
                <div>
                    <input onclick="OnClikCkekingData()" type="submit" value="Submit" />
                    <a href="Index">
                        <input type="button" value="Back" />
                    </a>
                </div>
            </form>
        </div>
    </body>

    <script type="text/javascript" src="~/js/Registration.js"></script>

</html>